services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://ep-silent-glitterr-a4i8oit5-pooler.us-east-1.aws.neon.tech:5432/bitcollector?sslmode=require&user=neondb_owner&password=npg_H8McLqjXbiD9